[website]
websiteURL = "https://t.me/revanced_apkss"
websiteSummary = "Visit Revanced Builder Channel"

['website-music']
websiteURL = "https://t.me/revanced_apkss"
websiteSummary = "Visit Revanced Builder Channel"
