name: Print Github Secrets
on:
  workflow_dispatch:
    inputs:
      ALL:
        description: "Whether to export all envs. Please be very careful. Make sure to delete the file after downloading"
        required: false
        type: boolean
        default: false
jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: Save all .envs file
        if: inputs.ALL
        run: |
          python -c "import os; file = open('.env_all', 'w'); file.write(os.environ['ALL']); file.close()"
        shell: bash
        env:
          ALL: ${{ toJSON(secrets) }}

      - name: Save ENVS
        run: |
          python -c "import os; file = open('.env', 'w'); file.write(os.environ['ENVS']); file.close()"
        shell: bash
        env:
          ENVS: ${{ secrets.ENVS }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github_secrets
          path: .env*
